### ISSUE TITLE
"Canada/East-Saskatchewan" was not recognized as a valid Windows time zone ID.

### ISSUE THREAD

**Issue by fernandolguevara** [mj1856/TimeZoneConverter#12]
Hi, I'm trying to run the code beloew and get 
**System.InvalidTimeZoneException: "Canada/East-Saskatchewan" was not recognized as a valid Windows time zone ID.**

```chsarp
return TZConvert.KnownIanaTimeZoneNames.Select(TZConvert.GetTimeZoneInfo)
                .OrderBy(tz => tz.BaseUtcOffset)
                .Select(tz => new NameValueDto
                {
                    Value = tz.Id,
                    Name =  tz.DisplayName
                }).ToList();
```

**Comment by mj1856** [comment]
Hi.  Sorry for the delayed response.

`Candada/East-Saskatchewan` was deliberately removed in the TZDB sources in 2017c.  See [the announcement](http://mm.icann.org/pipermail/tz-announce/2017-October/000047.html).  It is a breaking change for *many* downstream systems and has created some friction...

Basically, you should go through your data and replace all occurrences with `America/Regina`.  I don't do this automatically in my library because it's really not my place to police the TZDB.

Thanks.
