### ISSUE TITLE
Add support for new "Sao Tome Standard Time" windows timezone

### ISSUE THREAD

**Issue by MaceWindu** [mj1856/TimeZoneConverter#24]
https://blogs.technet.microsoft.com/dst2007/2018/03/30/time-zone-updates-for-morocco-brazil-sao-tome-and-principe/

looks like it is already pushed to some systems through windows update.

By support I mean IANA<->Windows conversion support

**Comment by mj1856** [comment]
Thanks.  I was waiting for the release notification, which appears to be delayed.  I'll investigate internally here at Microsoft and include this once I can confirm it was fully released.

Also, I think it may be worth waiting a little bit longer either way.  The last new time zone added ("Sudan Standard Time") resulted in some confusion [such as this](https://stackoverflow.com/q/47824619/634824) due to the update not yet being installed on the target machine where TimeZoneConverter was running.  I'm not quite sure what the right timing should be.

One idea to combat these competing concerns would be to start tracking version info here, with multiple mapping results depending on the data available on the target machine.  That's some work though.

**Comment by mj1856** [comment]
All good points.  I'm not interested in introducing a breaking change for that, but I'd consider adding it as a secondary API.  Think similarly to how `Parse` and `TryParse` coexist.

**Comment by mj1856** [comment]
(Will release shortly.)

**Comment by mj1856** [comment]
Both the "Try" APIs and the new time zone are added in version 2.4.0.  Thanks!

**Comment by MaceWindu** [comment]
Great! Thank you!
