### ISSUE TITLE
Daylight savings flag incorrectly set?

### ISSUE THREAD

**Issue by Jthomas54** [mj1856/TimeZoneConverter#44]
I'm using the `GetTimeZoneInfo` method with a zone of _Pacific/Honolulu_ and the `TimeZoneInfo` that it returned is correct except for the `SupportsDaylightsSavingsTime` field is marked as true.  

From my limited research, it doesn't appear Hawaii ever adopted DST so I would expect this field to be false.

**Comment by mj1856** [comment]
They did actually, back in the 1930s and 1940s.

https://www.timeanddate.com/time/zone/usa/honolulu?syear=1930&eyear=2020

https://github.com/eggert/tz/blob/2018i/northamerica#L696-L738


Since Windows doesn't have time zone information going back that far for this zone, `TimeZoneInfo.SupportsDaylightSavingTime` will return false on Windows and true on non-Windows OS.
