### ISSUE TITLE
Possible wrong Iana to Windows conversion for "Atlantic/Canary" ?

### ISSUE THREAD

**Issue by JaviPalla** [mj1856/TimeZoneConverter#51]
We are experiencing issues with users with Iana "Atlantic/Canary" timezone. The conversion returns "GMT Standard Time" and as I've researched current time in London (the example case) is UTC+1. 

In this link I can see that London has GMT Standard Time, but current time does not match current time in London (I think they may have a different timezone for summer):
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones

Does this library match the differences between summer and winter timezones? I'm using moment-timezone in client and it seems to be returning the correct time and timezone ("Atlantic/Canary", https://www.zeitverschiebung.net/es/timezone/atlantic--canary).

The problem is this inconsistency between server and client side timezones

Thanks for your time and for this useful library!

**Comment by mj1856** [comment]
The mapping is correct.  You can see it in the CLDR [here](
https://github.com/unicode-org/cldr/blob/c1802393839bf53929a95f38174d5ee2b8b78e62/common/supplemental/windowsZones.xml#L273):

```xml
<mapZone other="GMT Standard Time" territory="ES" type="Atlantic/Canary"/>
```

I think your confusion lies in this part of your question:

> Does this library match the differences between summer and winter timezones?

Both `"Atlantic/Canary"` and `"GMT Standard Time"` are IDs of time zones.  Each of those time zones consists of the entire set of time zone offset and transitions for between them.  One doesn't have a different time zone in the summer or in the winter, just a different offset within the same time zone.  `+00:00` and `+01:00` are *offsets*, not time zones unto themselves.

Keep in mind that the IDs for Windows time zones are confusing because they often contain the word "Standard".  Don't pay any attention to that.

As another example, I am in the US in the Pacific time zone.  The zone is commonly called Pacific Standard Time (PST) in the winter, and Pacific Daylight Time (PDT) in the summer.  PST has an offset of `-08:00` and PDT has an offset of `-07:00`.  The IANA identifier for the Pacific time zone is `"America/Los_Angeles"` and the Windows identifier is `"Pacific Standard Time"`.  There is no Windows identifier of `"Pacific Daylight Time"` - the same ID refers to both PST and PDT, depending on which is applicable for a given point in time.

You might also want to read: https://stackoverflow.com/tags/timezone/info
