### ISSUE TITLE
POSIX string returns format possibly not supported by the specification

### ISSUE THREAD

**Issue by smuellener** [mj1856/TimeZoneConverter#52]
FromIanaTimeZoneName("Asia/Yangon") returns "<+0630>-6:30". I can not find this format in the any POSIX timezone specification. Is this an official format and where can I find the specifications for it? If it is not an official format: How could this be handled to follow the specifications?

**Comment by mj1856** [comment]
This format is allowed by the POSIX spec.

The [TZDB 2016b announcement](https://mm.icann.org/pipermail/tz-announce/2016-March/000036.html) explains that numeric timestamps conform with POSIX.1-2001 and greater.

The current version, POSIX.1-2017 (IEEE Std 1003.1-2017) states (in the definition of the `TZ` variable, with regard to `std and dst` parts (the abbreviations)):

> Indicate no less than three, nor more than {TZNAME_MAX}, bytes that are the designation for the standard (std) or the alternative (dst—such as Daylight Savings Time) timezone. Only std is required; if dst is missing, then the alternative time does not apply in this locale.
>
> Each of these fields may occur in either of two formats quoted or unquoted:
> - In the quoted form, the first character shall be the <lessthan-sign> ('<') character and the last character shall be the <greater-than-sign> ('>') character. All characters between these quoting characters shall be alphanumeric characters from the portable character set in the current
locale, the <plus-sign> ('+') character, or the <hyphenminus> ('−') character. The std and dst fields in this case shall not include the quoting characters.
> - In the unquoted form, all characters in these fields shall be alphabetic characters from the portable character set in the current locale.

Thus, when a numeric abbreviation is used by the TZDB (such as `+0630`), POSIX requires it be quoted as `<+0630>` by the first form.

The remaining portion of the string conforms with the `offset` definition in the spec:

> Indicates the value added to the local time to arrive at Coordinated Universal Time. The offset has the form:
>
> `hh[:mm[:ss]]`
>
> The minutes (mm) and seconds (ss) are optional. The hour (hh) shall be required and may be a single digit. The offset following std shall be required. If no offset follows dst, the alternative time
is assumed to be one hour ahead of standard time. One or more digits may be used; the value is always interpreted as a decimal number. The hour shall be between zero and 24, and the minutes
(and seconds)—if present—between zero and 59. The result of using values outside of this range is unspecified. If preceded by a '−', the timezone shall be east of the Prime Meridian; otherwise, it shall be west (which may be indicated by an optional preceding '+').

Thus, the full string `<+0630>-06:30` is POSIX compliant, where the first quoted part is the abbreviation (using positive offset east of the prime meridian, since that's the typical ISO 8601 convention and the value returned from the TZDB), and the second unquoted part is the POSIX offset, having a negative value being east of the prime meridian since that's required by POSIX.

**Comment by mj1856** [comment]
One can also read this in the free HTML version available here:
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_03

Section 8.3 defines the TZ variable, among other variables.
