### ISSUE TITLE
Nuget package doesn't have a license info

### ISSUE THREAD

**Issue by sergey-meku** [mj1856/TimeZoneConverter#55]
Releases starting with 2.5.1 don't have a license info provided in nuget package.

**Comment by mj1856** [comment]
Hmm.. Well, everything is MIT licensed, per the license.txt file in the repo, but I get that it should also be in the package.

I specify the package license [in the csproj](https://github.com/mj1856/TimeZoneConverter/blob/master/src/TimeZoneConverter/TimeZoneConverter.csproj#L10), but I think perhaps it is supposed to be `<PackageLicenseExpression>` rather than just `<PackageLicense>`, per [these docs](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#packagelicenseexpression).  Not sure when that changed, but I can update on the next release.
