### ISSUE TITLE
Yukon Standard Time - IANA time zone conversion

### ISSUE THREAD

**Issue by gregsdennis** [mj1856/TimeZoneConverter#82]
When you added the Yukon time zone, how did you determine which IANA time zones go in it?  I saw your [PR](https://github.com/unicode-org/cldr/pull/842) to update CLDR, which included those mappings, but I'm curious where those mappings come from.

We have customers in those time zones which claim they should be mapped to Mountain Standard Time instead.  The difference is 1-2 hours depending on DST.

See also: [America/Dawson_Creek](https://www.zeitverschiebung.net/en/timezone/america--dawson_creek) and [America/Dawson](https://www.zeitverschiebung.net/en/timezone/america--dawson)

**Comment by gregsdennis** [comment]
Searching in the [IANA files](https://www.iana.org/time-zones), I found this:

```
Zone America/Dawson	-9:17:40 -	LMT	1900 Aug 20
			-9:00	NT_YK	Y%sT	1973 Oct 28  0:00
			-8:00	NT_YK	P%sT	1980
			-8:00	Canada	P%sT	2020 Nov  1
			-7:00	-	MST
```

But I'm not sure how to interpret it.

**Comment by mj1856** [comment]
Hi,

All of the IANA zones in the PR were already associated with the Yukon region, and indeed follow MST now (as seen in the last line you pasted).   The CLDR change doesn't modify that, but rather it maps them to a new Windows time zone that was established specifically for the affected areas.

The confusion perhaps may come from the way Windows time zones are labeled.  From the end-user's perspective, the government's name of the time zone is indeed now "Mountain Standard Time".  However, it can't be mapped to the *Windows* time zone with the ID of `"Mountain Standard Time"` because that is for regions that switch between MST and MDT - which Yukon no longer does.  It also can no longer be mapped to the Windows time zone with the ID of `"US Mountain Standard Time"` because it wouldn't accurately reflect the recent history of changes there.  Thus, Microsoft followed [it's policy on these matters](https://aka.ms/time) and established a new Windows time zone entry.

That entry has a *display name* of "(UTC-07:00) Yukon" (in English), and was delivered to computers through Windows Updates starting in August 2020 [per the announcement here](https://techcommunity.microsoft.com/t5/daylight-saving-time-time-zone/2020-time-zone-updates-for-yukon-now-available/ba-p/1598976).  It also has an *ID* of "Yukon Standard Time", which is used for things like the `Id` property of .NET's `TimeZoneInfo` class, and with command line utilities like `tzutil.exe`, and a few other things.

If your customers still believe they should be switching between MST and MDT, they're likely incorrect.  You can point them at https://www.timeanddate.com/news/time/yukon-canada-permanent-dst.html and https://legislation.yukon.ca/regs/oic2020_125.pdf.  If there are some edge cases we're not aware of, then please bring that up on the [tz discussion list](https://mm.icann.org/mailman/listinfo/tz) with details.

Does that help?

**Comment by mj1856** [comment]
Also, while it was well understood Yukon would be staying in UTC-7, there was indeed some confusion about what that would be called.  Originally it was referred to as permanent PDT (Pacific Daylight Time year round).  Later, on the IANA discussion threads, it was clarified that the original switch from PST to PDT was part of the original law, and the new law would keep the time zone on UTC-7 but it would be referred to as MST.  You can see this also in the following graphic:

https://www.timeanddate.com/time/zone/canada/whitehorse

![image](https://user-images.githubusercontent.com/1396388/102280576-44a30f00-3ee2-11eb-8359-3814c94e700b.png)

**Comment by gregsdennis** [comment]
Thank you.  That gives a lot of good context to the issue we're facing.

**Comment by mj1856** [comment]
Glad to help.  Also, I updated the above to show both 2020 and 2021.
