### ISSUE TITLE
Inconsistent daylight savings flag when running on Linux containers

### ISSUE THREAD

**Issue by lanegoolsby** [mj1856/TimeZoneConverter#85]
I am seeing inconsistent daylight savings flags for MST when using TzConvert on Linux vs Windows. 

The following code produces a True for `zoneInfo.SupportsDaylightSavingTime` on Linux but False (the correct value) on Windows. 

````
        internal static TimeZone MapTimeZone(float latitude, float longitude)
        {
            var zone = TimeZoneLookup.GetTimeZone(latitude, longitude);
            var zoneInfo = TZConvert.GetTimeZoneInfo(zone.Result);

            return new TimeZone
            {
                DaylightSavingsIndicator = zoneInfo.SupportsDaylightSavingTime,
                Name = zoneInfo.DisplayName,
                StandardUtcOffset = zoneInfo.BaseUtcOffset.Hours.ToString(),
                TxDatabaseName = zoneInfo.StandardName
            };
        }
````

Attached is a reproduction of the issue. [TzIssue.zip](https://github.com/mj1856/TimeZoneConverter/files/5810787/TzIssue.zip)

Run the app through the IDE debugger and you'll see this:
![image](https://user-images.githubusercontent.com/10758510/104503118-82548f80-5595-11eb-81c8-1df2dd986978.png)

But if you run it using Docker (`docker build -t tzissue . && docker run tzissue`) you'll get this:
![image](https://user-images.githubusercontent.com/10758510/104503199-9ef0c780-5595-11eb-81b8-f8f3e0d3919e.png)

**Comment by mj1856** [comment]
Hi.  I don't own `TimeZoneInfo`.  That is part of .NET itself.  If you feel there's a problem with it, you can log an issue at https://github.com/dotnet/runtime/issues.

That said, there's no promise that time zones on Windows are the same as they are on Linux.  Also, looking at your code:

- `SupportsDaylightSavingTime` just means that there are *any* adjustment rules for the time zone.  You probably wanted `IsDaylightSavingTime` instead, which will need a specific timestamp as input.
- You shouldn't take `Hours` out of the `BaseUtcOffset`.  There are several time zones that aren't in terms of whole hours.
- You likely wanted `GetUtcOffset` instead of `BaseUtcOffset`, though hard to tell without context.
- The `StandardNBame` will always be localized by the OS language settings.  You likely wanted an `Id` instead, which is not localized.
