### ISSUE TITLE
America/Creston is US Mountain Standard Time, but is hard-coded to be in Yukon

### ISSUE THREAD

**Issue by KereyWatters** [mj1856/TimeZoneConverter#87]
https://github.com/mj1856/TimeZoneConverter/blob/3e9d0363b4c986e9d8cb9f388fb91210bdc86167/src/TimeZoneConverter.DataBuilder/Program.cs#L52
https://github.com/mj1856/TimeZoneConverter/blob/3e9d0363b4c986e9d8cb9f388fb91210bdc86167/src/TimeZoneConverter.DataBuilder/Program.cs#L54

I'm not sure if others in the line are affected.
Are these hard-coded because the IANA databases don't have Yukon yet?

**Comment by gregsdennis** [comment]
Related to #82

**Comment by mj1856** [comment]
Hmmm..   I can see that CLDR also thinks Creston is aligned with `Yukon Standard Time`.  

https://github.com/unicode-org/cldr/blob/2287a76372f3fb82bff73e4ecef9a5c840c54d47/common/supplemental/windowsZones.xml#L84

However, I think you are correct.  Looking at IANA data, Creston appears to have been fixed to UTC-7 since 1918.  Thus it would align better with `US Mountain Standard Time`

https://github.com/eggert/tz/blob/2021a/northamerica#L2147-L2150

TimeAndData concurs with IANA

https://www.timeanddate.com/time/zone/canada/creston?syear=1900&eyear=2030

I will bring this up with CLDR.  Assuming they accept the change I will make sure TimeZoneConverter matches.  Thanks!

**Comment by mj1856** [comment]
See https://unicode-org.atlassian.net/browse/CLDR-14435

**Comment by mj1856** [comment]
Complete in version 3.4.0.
