### ISSUE TITLE
"Canada/East-Saskatchewan" Timezone not found in nodatime

### ISSUE THREAD

**Issue by erwan-joly** [mj1856/TimeZoneConverter#89]
HI I've been trying to resolve the Tzdb for the timezone `Canada/East-Saskatchewan` I'm getting from https://github.com/mj1856/TimeZoneConverter and it doesn't seems to resolve in nodatime.
Is that an expected timezoneId  ?

what I found searching on google is that the name in multiple places is just `Canada/Saskatchewan` because it was too long https://ftp.iana.org/tz/tzdb-2018b/NEWS

NodaTime seems to use `Canada/Saskatchewan` and error on `Canada/East-Saskatchewan`

CF https://github.com/nodatime/nodatime/issues/1615

**Comment by mj1856** [comment]
It used to be an IANA link name, but was removed in 2017c when the max-length for zones and links was set to 14 characters.
https://github.com/eggert/tz/commit/d5054b62469ef1b1b0cea3192f6cc814ade989d9

It's in TimeZoneConverter deliberately, because TimeZoneConverter is often used to accommodate time zone ids coming from lots of different sources, some of which may still have the old ID.

If it's creating a problem, would you please clarify how you are using it?

I would consider perhaps removing it from `KnownIanaTimeZoneNames`, but I would still want it to work with `IanaToWindows` and other conversion methods.

**Comment by mj1856** [comment]
Ok, I've thought about this a bit, and I've decided it makes sense for `Canada/East-Saskatchewan` (and `US/Pacific-New` for the same reasons) to be omitted from `KnownIanaTimeZoneNames`, but should still pass through `IanaToWindows` correctly.

**Comment by mj1856** [comment]
For similar reasons I'm also going to omit `Kamchatka Standard Time` and `Mid-Atlantic Standard Time` from `KnownWindowsTimeZoneIds`.  They have both been marked obsolete in the Windows Registry for quite some time.

**Comment by mj1856** [comment]
Complete in version 3.4.0.
